/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Koneksidb;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lenov
 */
public class DataObat extends javax.swing.JFrame {

    Konek konek=new Konek();
    
    private DefaultTableModel model;
    
    private void autonumber(){
        try {
            Connection c=konek.getkonek();
            Statement s=c.createStatement();
            String sql="SELECT * FROM barang ORDER BY ID_barang DESC";
            ResultSet r=s.executeQuery(sql);
            if(r.next()){
                String nofaktur=r.getString("ID_barang").substring(2);
                String BR=""+(Integer.parseInt(nofaktur)+1);
                String No1="";
                
                if(BR.length()==1)
                {No1="00";}
                else if(BR.length()==2)
                {No1="0";}
                else if(BR.length()==3)
                {No1="";}
                TXTIDOBAT.setText("BR" + No1 + BR);
            }else{
                TXTIDOBAT.setText("BR001");
            }
            r.close();
            s.close();
        } catch (Exception e) {
            System.out.println();
        }
    }
    
    public void clear(){
        TXTNAMA.setText("");
        TXTBELI.setText("");
        TXTJUAL.setText("");
        TXTSTOK.setText("");
    }
    
    public void loaddata(){
        model.getDataVector().removeAllElements();
        
        model.fireTableDataChanged();
        
        try {
            Connection c=konek.getkonek();
            Statement s=c.createStatement();
            String sql="SELECT * FROM barang";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()){
                Object[]o=new Object[6];
                o[0]=r.getString("ID_barang");
                o[1]=r.getString("nama_barang");
                o[2]=r.getString("jenis");
                o[3]=r.getString("hargabeli");
                o[4]=r.getString("hargajual");
                o[5]=r.getString("stok");
                
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (Exception e) {
            System.out.println("terjadi kesalahan");
        }
    }
    
    public void caridata(){
        DefaultTableModel tabel=new DefaultTableModel();
        
        tabel.addColumn("ID_barang");
        tabel.addColumn("nama_barang");
        tabel.addColumn("jenis");
        tabel.addColumn("hargabeli");
        tabel.addColumn("hargajual");
        tabel.addColumn("stok");
        
        try {
            Connection c=konek.getkonek();
            String sql="select * from barang where ID_barang like '%" + TXTIDOBAT.getText()+"%'"+
                    "or nama_barang like '%"+TXTNAMA.getText()+"%'";
            Statement s=c.createStatement();
            ResultSet r=s.executeQuery(sql);
            while (r.next()){
                tabel.addRow(new Object[]{
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                });  
            }
            jTable1.setModel(tabel);
            loaddata();
            
        } catch (Exception e) {
            System.out.println("cari data error");
        }finally{
            
        }  
    }
    
    
    /**
     * Creates new form DataObat
     */
    public DataObat() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        model=new DefaultTableModel();
        jTable1.setModel(model);
        
        model.addColumn("ID_barang");
        model.addColumn("nama_barang");
        model.addColumn("jenis");
        model.addColumn("hargabeli");
        model.addColumn("hargajual");
        model.addColumn("stok");
        
        loaddata();
        autonumber();
        BTNEDIT.setEnabled(false);
        BTNHAPUS.setEnabled(false);
        BTNBATAL.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTCARI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTIDOBAT = new javax.swing.JTextField();
        TXTNAMA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXTBELI = new javax.swing.JTextField();
        TXTJUAL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXTSTOK = new javax.swing.JTextField();
        BTNSAVE = new javax.swing.JButton();
        CMBJENIS = new javax.swing.JComboBox<>();
        BTNEDIT = new javax.swing.JButton();
        BTNHAPUS = new javax.swing.JButton();
        BTNBATAL = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DATA OBAT");

        jLabel2.setText("CARI DATA");

        jLabel3.setText("ID OBAT");

        jLabel4.setText("NAMA OBAT");

        jLabel5.setText("JENIS");

        jLabel6.setText("HARGA BELI");

        jLabel7.setText("HARGA JUAL");

        jLabel8.setText("STOK");

        BTNSAVE.setText("SIMPAN");
        BTNSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSAVEActionPerformed(evt);
            }
        });

        CMBJENIS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OBAT OLES", "KAPSUL", "TABLET", "OBAT CAIR" }));

        BTNEDIT.setText("EDIT");
        BTNEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITActionPerformed(evt);
            }
        });

        BTNHAPUS.setText("HAPUS");
        BTNHAPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHAPUSActionPerformed(evt);
            }
        });

        BTNBATAL.setText("BATAL");
        BTNBATAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBATALActionPerformed(evt);
            }
        });

        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel2))
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTCARI, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTJUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTSTOK, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTBELI, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TXTIDOBAT)
                                .addComponent(TXTNAMA, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addComponent(CMBJENIS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTNEDIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNSAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNHAPUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNBATAL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXTIDOBAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TXTNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CMBJENIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTCARI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TXTBELI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTJUAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TXTSTOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNSAVE)
                        .addGap(25, 25, 25)
                        .addComponent(BTNEDIT)
                        .addGap(18, 18, 18)
                        .addComponent(BTNHAPUS)
                        .addGap(18, 18, 18)
                        .addComponent(BTNBATAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITActionPerformed
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        if(i==-1){
            return;
        }
        String id=(String)model.getValueAt(i, 0);
        String nama=TXTNAMA.getText();
        String jenis=(String)CMBJENIS.getSelectedItem();
        String hargabeli=TXTBELI.getText();
        String hargajual=TXTJUAL.getText();
        String stok=TXTSTOK.getText();
        
        try {
            Connection c=Konek.getkonek();
            String sql="UPDATE barang SET nama_barang=?, jenis=?, hargabeli=?, hargajual=?, stok=? WHERE ID_barang=?";
            PreparedStatement p=c.prepareStatement(sql);
            p.setString(1, nama);
            p.setString(2, jenis);
            p.setString(3, hargabeli);
            p.setString(4, hargajual);
            p.setString(5, stok);
            p.setString(6, id);
            
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "data terubah");
            BTNSAVE.setEnabled(true);
            BTNEDIT.setEnabled(false);
            BTNHAPUS.setEnabled(false);
            BTNBATAL.setEnabled(false);
            clear();
        } catch (Exception e) {
            System.out.println("update eror");
        }finally{
            loaddata();
            autonumber();
        }
    }//GEN-LAST:event_BTNEDITActionPerformed

    private void BTNHAPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHAPUSActionPerformed
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        if(i==-1){
            return;
        }
        String id=(String)model.getValueAt(i, 0);
        
        int pernyataan=JOptionPane.showConfirmDialog(null, "yakin dihapus???","konfirmasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(pernyataan==JOptionPane.OK_OPTION){
            try {
                Connection c=konek.getkonek();
                String sql="DELETE FROM barang WHERE ID_barang=?";
                PreparedStatement p=c.prepareStatement(sql);
                p.setString(1, id);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(null, "data terhapus");
            } catch (Exception e) {
                System.out.println("terjadi kesalahan");
            }finally{
                BTNSAVE.setEnabled(true);
                BTNEDIT.setEnabled(false);
                BTNHAPUS.setEnabled(true);
                BTNBATAL.setEnabled(false);
                loaddata();
                autonumber();
                clear();
            }
        }
        if(pernyataan==JOptionPane.CANCEL_OPTION){
            
        }
    }//GEN-LAST:event_BTNHAPUSActionPerformed

    private void BTNSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSAVEActionPerformed
        // TODO add your handling code here:
        String id=TXTIDOBAT.getText();
        String nama=TXTNAMA.getText();
        String jenis=(String)CMBJENIS.getSelectedItem();
        String hargabeli=TXTBELI.getText();
        String hargajual=TXTJUAL.getText();
        String stok=TXTSTOK.getText();
        
        try {
            Connection c=konek.getkonek();
            String sql="INSERT INTO barang VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement p=c.prepareStatement(sql);
            p.setString(1, id);
            p.setString(2, nama);
            p.setString(3, jenis);
            p.setString(4, hargabeli);
            p.setString(5, hargajual);
            p.setString(6, stok);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "data tersimpan");
            loaddata();
        } catch (Exception e) {
            System.out.println("terjadi kesalahn");
        }finally{
            autonumber();
            clear();
        }
    }//GEN-LAST:event_BTNSAVEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        BTNSAVE.setEnabled(false);
        BTNEDIT.setEnabled(true);
        BTNHAPUS.setEnabled(true);
        BTNBATAL.setEnabled(true);
        
        int i=jTable1.getSelectedRow();
        if(i==-1){
            return;
        }
        String id=(String)model.getValueAt(i, 0);
        String nama=(String)model.getValueAt(i, 1);
        String jenis=(String)model.getValueAt(i, 2);
        String hargabeli=(String)model.getValueAt(i, 3);
        String hargajual=(String)model.getValueAt(i, 4);
        String stok=(String)model.getValueAt(i, 5);
        
        TXTIDOBAT.setText(id);
        TXTNAMA.setText(nama);
        CMBJENIS.setSelectedItem(jenis);
        TXTBELI.setText(hargabeli);
        TXTJUAL.setText(hargajual);
        TXTSTOK.setText(stok);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void BTNBATALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBATALActionPerformed
        // TODO add your handling code here:
        clear();
        loaddata();
        BTNSAVE.setEnabled(true);
        BTNEDIT.setEnabled(false);
        BTNHAPUS.setEnabled(false);
        BTNBATAL.setEnabled(false);
        autonumber();
    }//GEN-LAST:event_BTNBATALActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuUtama dataobat= new MenuUtama();
       dataobat.setLocationRelativeTo(this);
       dataobat.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBATAL;
    private javax.swing.JButton BTNEDIT;
    private javax.swing.JButton BTNHAPUS;
    private javax.swing.JButton BTNSAVE;
    private javax.swing.JComboBox<String> CMBJENIS;
    private javax.swing.JTextField TXTBELI;
    private javax.swing.JTextField TXTCARI;
    private javax.swing.JTextField TXTIDOBAT;
    private javax.swing.JTextField TXTJUAL;
    private javax.swing.JTextField TXTNAMA;
    private javax.swing.JTextField TXTSTOK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
