/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Koneksidb;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lenov
 */
public class PenjualanObat extends javax.swing.JFrame {
String Tanggal;
    private DefaultTableModel model;
    
    public void totalbayar(){
        int jumlahBaris=jTable1.getRowCount();
        int totalbiaya=0;
        int jumlahBarang, hargaBarang;
        for (int i = 0; i < jumlahBaris; i++) {
            jumlahBarang=Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            hargaBarang=Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            totalbiaya=totalbiaya + (jumlahBarang * hargaBarang);
        }
        TXTTOTAL.setText(String.valueOf(totalbiaya));
        TXTTAMPIL.setText("RP"+ totalbiaya +",00");
    }
    private void autonumber(){
        try{
            Connection c= Konek.getkonek();
            Statement st=c.createStatement();
            String sql="SELECT * FROM obat2 ORDER BY nofaktur DESC";
            ResultSet rs=st.executeQuery(sql);
            if(rs.next()){
                String nofaktur=rs.getString("nofaktur").substring(2);
                String TR=""+(Integer.parseInt(nofaktur)+1);
                String No1="";
                
                if(TR.length()==1)
                {No1="000";}
                else if(TR.length()==2)
                {No1="00";}
                else if(TR.length()==3)
                {No1="0";}
                else if(TR.length()==4)
                {No1="";}
                TXTFAKTUR.setText("TR"+ No1 + TR);
            }else{
                 TXTFAKTUR.setText("TR0001");
            }
            rs.close();
            st.close();
        }catch (Exception e){
            System.out.println("autonumber error");
        }
    }
    
    public void loaddata(){
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{
            TXTFAKTUR.getText(),
            TXTIDBARANG.getText(),
            TXTNAMABARANG.getText(),
            TXTJUMLAH.getText(),
            TXTHARGA.getText(),
            TXTTOTAL.getText()
        });
    }
    
    public void kosong(){
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         
         while (model.getRowCount()>0){
             model.removeRow(0);
         }
    }
    
    public void utama(){
        TXTFAKTUR.setText("");
        TXTIDBARANG.setText("");
        TXTNAMABARANG.setText("");
        TXTHARGA.setText("");
        TXTJUMLAH.setText("");
        autonumber();
    }
    
    public void clear (){
        TXTIDCUSTOMER.setText("");
        TXTNAMACUSTOMER.setText("");
        TXTTOTAL.setText("0");
        TXTBAYAR.setText("0");
        TXTKEMBALIAN.setText("0");
        TXTTAMPIL.setText("0");
        
    }
    
    public void clear2(){
        TXTIDBARANG.setText("");
        TXTNAMABARANG.setText("");
        TXTHARGA.setText("");
        TXTJUMLAH.setText("");
    }
    
    public void tambahTransaksi(){
        int jumlah, harga, total;
        jumlah=Integer.valueOf(TXTJUMLAH.getText());
        harga=Integer.valueOf(TXTHARGA.getText());
        total=jumlah * harga;
        
        TXTTOTAL.setText(String.valueOf(total));
        
        loaddata();
        totalbayar();
        clear2();
        TXTIDBARANG.requestFocus();
    }
    
    
    /**
     * Creates new form PenjualanObat
     */
    public PenjualanObat() {
        initComponents();
        
        model=new DefaultTableModel();
        
        jTable1.setModel(model);
        
        model.addColumn("no transaksi");
        model.addColumn("id OBAT");
        model.addColumn("nama OBAT");
        model.addColumn("jumlah");
        model.addColumn("harga");
        model.addColumn("total");
        
        utama();
        Date date=new Date();
        SimpleDateFormat st=new SimpleDateFormat("dd-mm-yyyy");
        
        TXTTGL.setText(st.format(date));
        TXTTOTAL.setText("0");
        TXTBAYAR.setText("0");
        TXTKEMBALIAN.setText("0");
        TXTIDCUSTOMER.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXTFAKTUR = new javax.swing.JTextField();
        TXTIDCUSTOMER = new javax.swing.JTextField();
        TXTNAMACUSTOMER = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TXTTAMPIL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TXTTOTAL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTBAYAR = new javax.swing.JTextField();
        TXTKEMBALIAN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXTTGL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TXTIDBARANG = new javax.swing.JTextField();
        TXTNAMABARANG = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TXTHARGA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TXTJUMLAH = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        BTNCARI = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("no transaksi");

        jLabel3.setText("id customer");

        jLabel4.setText("nama customer");

        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TXTTAMPIL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        TXTTAMPIL.setText("Rp");

        jLabel5.setText("TOTAL BAYAR");

        jLabel2.setText("BAYAR");

        jLabel6.setText("KEMBALIAN");

        TXTBAYAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBAYARActionPerformed(evt);
            }
        });

        jLabel7.setText("TANGGAL");

        jLabel8.setText("ID OBAT");

        jLabel9.setText("NAMA OBAT");

        jLabel10.setText("HARGA");

        jLabel11.setText("JUMLAH");

        TXTJUMLAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTJUMLAHActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("PENJUALAN");

        BTNCARI.setText("CARI");
        BTNCARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCARIActionPerformed(evt);
            }
        });

        jButton4.setText("KELUAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXTTAMPIL, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTKEMBALIAN)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTBAYAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTTOTAL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(jButton4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(TXTIDBARANG, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TXTFAKTUR, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                            .addComponent(TXTIDCUSTOMER)
                                            .addComponent(TXTNAMACUSTOMER))
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(BTNCARI)
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(TXTNAMABARANG, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel7)
                                        .addGap(56, 56, 56)
                                        .addComponent(TXTTGL, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(TXTHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(TXTJUMLAH, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(254, 254, 254)))
                        .addGap(5, 5, 5)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTFAKTUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(TXTTGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTIDCUSTOMER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTNAMACUSTOMER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTIDBARANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTNAMABARANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTHARGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTJUMLAH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCARI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(TXTTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(TXTBAYAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTTAMPIL, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TXTKEMBALIAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tambahTransaksi();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TXTJUMLAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTJUMLAHActionPerformed
        // TODO add your handling code here:
        tambahTransaksi();
    }//GEN-LAST:event_TXTJUMLAHActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int row=jTable1.getSelectedRow();
        model.removeRow(row);
        totalbayar();
        TXTBAYAR.setText("0");
        TXTKEMBALIAN.setText("0");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TXTBAYARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBAYARActionPerformed
        // TODO add your handling code here:
        int total, bayar, kembalian;
        
        total=Integer.valueOf(TXTTOTAL.getText());
        bayar=Integer.valueOf(TXTBAYAR.getText());
        
        if (total>bayar){
            JOptionPane.showMessageDialog(null, "uang tidak cukup untuk melakukan pembayaran");
        }else{
            kembalian=bayar-total;
            TXTKEMBALIAN.setText(String.valueOf(kembalian));
        }
    }//GEN-LAST:event_TXTBAYARActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
         
         String notransaksi=TXTFAKTUR.getText();
         String tanggal=TXTTGL.getText();
         String idcustomer=TXTIDCUSTOMER.getText();
         String total=TXTTOTAL.getText();
         
         try {
           Connection c= Konek.getkonek();
           String sql="INSERT INTO obat2 VALUES (?, ?, ?, ?)";
           PreparedStatement p=c.prepareStatement(sql);
           p.setString(1, notransaksi);
           p.setString(2, tanggal);
           p.setString(3, idcustomer);
           p.setString(4, total);
           p.executeUpdate();
           p.close();
        } catch (Exception e) {
            System.out.println("simpan penjualan eror");
        }
         try {
            Connection c= Konek.getkonek();
            int baris=jTable1.getRowCount();
            
             for (int i = 0; i < baris; i++) {

                String sql="INSERT INTO penjualan(nofaktur, ID_barang, nama_barang, jumlah, harga, total)VALUES ('"
                        + jTable1.getValueAt(i, 0) +"','"+ jTable1.getValueAt(i, 1) +"','"+ jTable1.getValueAt(i, 2) +"','"
                        + jTable1.getValueAt(i, 3) +"','"+ jTable1.getValueAt(i, 4) +"','"+ jTable1.getValueAt(i, 5) +"')";
                PreparedStatement p=c.prepareStatement(sql);
                p.executeUpdate();
                p.close();
            }
                    
        } catch (Exception e) {
            System.out.println("simpan penjualan eror");
        }
         clear();
         utama();
         autonumber();
         kosong();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BTNCARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCARIActionPerformed
        // TODO add your handling code here:
        ListObat a=new ListObat();
        a.setVisible(true);
    }//GEN-LAST:event_BTNCARIActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MenuUtama dataobat= new MenuUtama();
       dataobat.setLocationRelativeTo(this);
       dataobat.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCARI;
    private javax.swing.JTextField TXTBAYAR;
    private javax.swing.JTextField TXTFAKTUR;
    public static javax.swing.JTextField TXTHARGA;
    public static javax.swing.JTextField TXTIDBARANG;
    private javax.swing.JTextField TXTIDCUSTOMER;
    private javax.swing.JTextField TXTJUMLAH;
    private javax.swing.JTextField TXTKEMBALIAN;
    public static javax.swing.JTextField TXTNAMABARANG;
    private javax.swing.JTextField TXTNAMACUSTOMER;
    private javax.swing.JTextField TXTTAMPIL;
    private javax.swing.JTextField TXTTGL;
    private javax.swing.JTextField TXTTOTAL;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
